[tool.poetry]
name = "orm-benchmark"
version = "0.1.0"
description = ""
authors = ["sdhou <xiaohou.don@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
SQLAlchemy = "^2.0.29"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
